In [3]:
import pandas as pd

In [31]:
df_studentloanforgiveness = pd.read_csv('student_loan_forgiveness.csv')
df_studentdebtbomb = pd.read_csv('student_debt_bomb.csv')
df_loanforgiveness = pd.read_csv('loan_forgiveness.csv')
df_studentloandebt = pd.read_csv('student_loan_debt.csv')
df_studentdebt = pd.read_csv('student_debt.csv')
df_studentloan = pd.read_csv('student_loan.csv')

In [33]:
frames = [df_studentloanforgiveness, df_studentdebtbomb, df_loanforgiveness, df_studentloandebt, df_studentdebt, df_studentloan]
  
df = pd.concat(frames)

display(df)

print(len(df))

,Unnamed: 0,Date,User Name,User ID,Tweet,User Location,Image URL
0,0,2022-12-06 23:57:15+00:00,FleursMackinac,1129803418376318978,@DebtCrisisOrg @POTUS Hey @POTUS how about you...,NaN,https://pbs.twimg.com/profile_images/112980375...
1,1,2022-12-06 23:26:24+00:00,MystoryReright,1500480417086033920,"♦️Beware of the temptations♦️\n\nThe truth is,...","Springfield Gardens, NY",https://pbs.twimg.com/profile_images/150048167...
2,2,2022-12-06 23:23:56+00:00,karenggolden,494178784,@joebiden knew exactly what he was doing offer...,NaN,https://pbs.twimg.com/profile_images/150925550...
3,3,2022-12-06 23:14:43+00:00,Demi_Libman,1589486554875060225,Conservatives are so uneducated they don't eve...,"Palo Alto, CA",https://pbs.twimg.com/profile_images/158949402...
4,4,2022-12-06 23:06:03+00:00,CassieRaeDuBay,995856763,"I haven't seen any updated clock, so throwing ...","Dallas, TX",https://pbs.twimg.com/profile_images/138272017...
...,...,...,...,...,...,...,...
2676,2676,2022-09-15 04:26:29+00:00,InCredFin,896974990074970112,Tag your engineer friend who is just a call aw...,India,https://pbs.twimg.com/profile_images/134609249...
2677,2677,2022-09-15 04:25:23+00:00,Iammudude20,1217412988451225600,Go check out Lorien Finance for easy loans to ...,NaN,https://pbs.twimg.com/profile_images/137900311...
2678,2678,2022-09-15 02:22:17+00:00,TrillDoom,1564762503011336192,All this #karaoke got me #something #hungry ;...,SlipSpace,https://pbs.twimg.com/profile_images/159648319...
2679,2679,2022-09-15 00:42:02+00:00,LAFosterYouth,1021045159729901568,Repost from @laco_dpss Are Student Loans weigh...,"Los Angeles County, CA",https://pbs.twimg.com/profile_images/102219266...
2680,2680,2022-09-15 00:10:55+00:00,TurnOnThePower,1235968368,Good! Republicans deserve to get beat due to t...,Western NC,https://pbs.twimg.com/profile_images/889980881...

20221

In [34]:
df['Location'] = 'United States'
df.drop(['User Location'], axis=1, inplace=True)
df.head(5)

,Unnamed: 0,Date,User Name,User ID,Tweet,Image URL,Location
0,0,2022-12-06 23:57:15+00:00,FleursMackinac,1129803418376318978,@DebtCrisisOrg @POTUS Hey @POTUS how about you...,https://pbs.twimg.com/profile_images/112980375...,United States
1,1,2022-12-06 23:26:24+00:00,MystoryReright,1500480417086033920,"♦️Beware of the temptations♦️\n\nThe truth is,...",https://pbs.twimg.com/profile_images/150048167...,United States
2,2,2022-12-06 23:23:56+00:00,karenggolden,494178784,@joebiden knew exactly what he was doing offer...,https://pbs.twimg.com/profile_images/150925550...,United States
3,3,2022-12-06 23:14:43+00:00,Demi_Libman,1589486554875060225,Conservatives are so uneducated they don't eve...,https://pbs.twimg.com/profile_images/158949402...,United States
4,4,2022-12-06 23:06:03+00:00,CassieRaeDuBay,995856763,"I haven't seen any updated clock, so throwing ...",https://pbs.twimg.com/profile_images/138272017...,United States

In [35]:
# Data Cleaning

# Using regex to clean the data

import re
import nltk
from nltk.corpus import stopwords

import numpy as np
import re

#df = pd.read_csv('fff.csv')

stopwords = set(stopwords.words('english'))

# stopwords.add('amp', 'AMP', '&amp', '&', '&AMP')
stopwords.add('amp')
stopwords.add('AMP')
stopwords.add('&')
stopwords.add('&amp')
stopwords.add('&AMP')


def clean_tweet(tweet):
    if type(tweet) == np.float:
        return ""
    temp = tweet.lower()
    temp = re.sub("'", "", temp) # to avoid removing contractions in english
    temp = re.sub("@[A-Za-z0-9_]+","", temp)
    temp = re.sub("#[A-Za-z0-9_]+","", temp)
    temp = re.sub(r'http\S+', '', temp)
    temp = re.sub('[()!?]', ' ', temp)
    temp = re.sub('\[.*?\]',' ', temp)
    #temp = re.sub("[^a-z0-9]"," ", temp) --> Doesn't remove numbers
    temp = re.sub("[^a-z]"," ", temp)    
    temp = temp.split()
    temp = [w for w in temp if not w in stopwords]
    temp = " ".join(word for word in temp)
    return temp

In [36]:
results = [clean_tweet(tw) for tw in df['Tweet']]
results[:10]
#df.head(10)

C:\Users\Arunaggiri Pandian\AppData\Local\Temp\ipykernel_29592\1204666790.py:25: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if type(tweet) == np.float:

['hey right thing millions americans',
 'beware temptations truth quite easy assume left hook quit paying student loan debt altogether even forgiveness doesnt happen bad idea serious consequences',
 'knew exactly offering',
 'conservatives uneducated dont even need student loans bailed government',
 'havent seen updated clock throwing oral arguments student loan forgiveness feb payment pause resumes april earliest yes days courts address plan right',
 '',
 'anyone student loan relief stance ppp loans',
 'tip loans via great lakes request refund using chat feature simply specify dates date range march current wait time refund request months please aware',
 'time wipe student loan debt create entirely new system',
 'heart drawing students']

In [37]:
#create new df from list

df['Cleaned_Tweet'] = results
df.head(5)

,Unnamed: 0,Date,User Name,User ID,Tweet,Image URL,Location,Cleaned_Tweet
0,0,2022-12-06 23:57:15+00:00,FleursMackinac,1129803418376318978,@DebtCrisisOrg @POTUS Hey @POTUS how about you...,https://pbs.twimg.com/profile_images/112980375...,United States,hey right thing millions americans
1,1,2022-12-06 23:26:24+00:00,MystoryReright,1500480417086033920,"♦️Beware of the temptations♦️\n\nThe truth is,...",https://pbs.twimg.com/profile_images/150048167...,United States,beware temptations truth quite easy assume lef...
2,2,2022-12-06 23:23:56+00:00,karenggolden,494178784,@joebiden knew exactly what he was doing offer...,https://pbs.twimg.com/profile_images/150925550...,United States,knew exactly offering
3,3,2022-12-06 23:14:43+00:00,Demi_Libman,1589486554875060225,Conservatives are so uneducated they don't eve...,https://pbs.twimg.com/profile_images/158949402...,United States,conservatives uneducated dont even need studen...
4,4,2022-12-06 23:06:03+00:00,CassieRaeDuBay,995856763,"I haven't seen any updated clock, so throwing ...",https://pbs.twimg.com/profile_images/138272017...,United States,havent seen updated clock throwing oral argume...

In [38]:
# Dropping rows that have empty values as tweets after data cleaning because without dropping those I can't use it in
# sentimentintensityanalyser() function, as it only accepts string input and empty values are of float type

print('Number of Tweets before data cleaning:', df.shape[0])

df.dropna(
    axis=0,
    how='any',
    thresh=None,
    subset=None,
    inplace=True
)

print('Number of Tweets after data cleaning:', df.shape[0])
#print(df['Cleaned_Tweet'][3])
df.head(3)

Number of Tweets before data cleaning: 20221
Number of Tweets after data cleaning: 20221

,Unnamed: 0,Date,User Name,User ID,Tweet,Image URL,Location,Cleaned_Tweet
0,0,2022-12-06 23:57:15+00:00,FleursMackinac,1129803418376318978,@DebtCrisisOrg @POTUS Hey @POTUS how about you...,https://pbs.twimg.com/profile_images/112980375...,United States,hey right thing millions americans
1,1,2022-12-06 23:26:24+00:00,MystoryReright,1500480417086033920,"♦️Beware of the temptations♦️\n\nThe truth is,...",https://pbs.twimg.com/profile_images/150048167...,United States,beware temptations truth quite easy assume lef...
2,2,2022-12-06 23:23:56+00:00,karenggolden,494178784,@joebiden knew exactly what he was doing offer...,https://pbs.twimg.com/profile_images/150925550...,United States,knew exactly offering

In [39]:
df.to_csv('Cleaned_Twitter_Data.csv')

In [40]:
import pandas as pd
df = pd.read_csv('Cleaned_Twitter_Data.csv')

In [41]:
# Dropping rows that have empty values as tweets after data cleaning because without dropping those I can't use it in
# sentimentintensityanalyser() function, as it only accepts string input and empty values are of float type

print('Number of Tweets before data cleaning:', df.shape[0])

df.dropna(
    axis=0,
    how='any',
    thresh=None,
    subset=None,
    inplace=True
)
print('Number of Tweets after data cleaning:', df.shape[0])
#print(df['Cleaned_Tweet'][3])
df.head(3)

Number of Tweets before data cleaning: 20221
Number of Tweets after data cleaning: 18558

,Unnamed: 0.1,Unnamed: 0,Date,User Name,User ID,Tweet,Image URL,Location,Cleaned_Tweet
0,0,0,2022-12-06 23:57:15+00:00,FleursMackinac,1129803418376318978,@DebtCrisisOrg @POTUS Hey @POTUS how about you...,https://pbs.twimg.com/profile_images/112980375...,United States,hey right thing millions americans
1,1,1,2022-12-06 23:26:24+00:00,MystoryReright,1500480417086033920,"♦️Beware of the temptations♦️\n\nThe truth is,...",https://pbs.twimg.com/profile_images/150048167...,United States,beware temptations truth quite easy assume lef...
2,2,2,2022-12-06 23:23:56+00:00,karenggolden,494178784,@joebiden knew exactly what he was doing offer...,https://pbs.twimg.com/profile_images/150925550...,United States,knew exactly offering

In [42]:
df.to_csv('Final_Cleaned_Twitter_Data.csv')